{% set name = "dagster_pandas" %}
{% set version = "0.6.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("_","-") }}-{{ version }}.tar.gz"
  sha256: d83dcf04d6b0109208f6111d53dc7946a252bc9fce252e890b1c96ca1853fab2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - matplotlib-base
    - pandas

test:
  imports:
    - dagster_pandas

about:
  home: "https://github.com/dagster-io/dagster"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Utilities and examples for working with pandas and dagster, an opinionated framework for expressing data pipelines"

extra:
  recipe-maintainers:
    - conda-forge/dagster
